name: Format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Format CC
        run: |
          uvx --from clang-format==18.1.8 clang-format --version
          git ls-files 'include/*.h' 'include/*.cc' | xargs -r uvx --from clang-format==18.1.8 clang-format --Werror --dry-run -i
