name: Test Linux

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          submodules: true
      - name: Environment Information
        run: npx envinfo
      - name: Config
        run: cmake -B out
      - name: Build
        run: make -C out -j$(nproc)
      - name: Test
        run: out/example.x -s
